import type { TriggerPayload } from "@prismatic-io/spectral";
const createdContactRecord = {
  id: 47912051,
  creator_id: 1290481,
  owner_id: 1290481,
  is_organization: false,
  contact_id: null,
  parent_organization_id: null,
  name: "Dana Lee",
  first_name: "Dana",
  last_name: "Lee",
  customer_status: "prospect",
  prospect_status: "current",
  title: "Director of Operations",
  description: "Inbound lead from Q2 webinar",
  industry: "Manufacturing",
  website: "https://www.brightworks.io",
  email: "dana.lee@brightworks.io",
  phone: "+1-312-555-0142",
  mobile: "+1-312-555-0143",
  fax: null,
  twitter: null,
  facebook: null,
  linkedin: "dana-lee-ops",
  skype: null,
  address: {
    line1: "118 Maple Ave",
    city: "Evanston",
    postal_code: "60201",
    state: "IL",
    country: "US",
  },
  billing_address: null,
  shipping_address: null,
  tags: ["new-lead"],
  custom_fields: {
    referred_by: "Webinar",
  },
  created_at: "2025-02-18T08:15:00Z",
  updated_at: "2025-02-18T08:15:00Z",
};
const updatedContactRecord = {
  id: 47912050,
  creator_id: 1290481,
  owner_id: 1290481,
  is_organization: false,
  contact_id: 47912048,
  parent_organization_id: null,
  name: "Mark Johnson",
  first_name: "Mark",
  last_name: "Johnson",
  customer_status: "current",
  prospect_status: "none",
  title: "VP of Sales",
  description: "Key decision maker for Q4 renewals",
  industry: "Technology",
  website: "https://www.acmecorp.io",
  email: "mark.johnson@acmecorp.io",
  phone: "+1-415-555-0198",
  mobile: "+1-415-555-0199",
  fax: "+1-415-555-0200",
  twitter: "markjohnson",
  facebook: "mark.johnson.sales",
  linkedin: "markjohnson-vpsales",
  skype: "mark.johnson.acme",
  address: {
    line1: "2726 Smith St",
    city: "Hainesville",
    postal_code: "60030",
    state: "IL",
    country: "US",
  },
  billing_address: {
    line1: "2726 Smith St",
    city: "Hainesville",
    postal_code: "60030",
    state: "IL",
    country: "US",
  },
  shipping_address: {
    line1: "2726 Smith St",
    city: "Hainesville",
    postal_code: "60030",
    state: "IL",
    country: "US",
  },
  tags: ["enterprise", "priority"],
  custom_fields: {
    referred_by: "Partner Channel",
  },
  created_at: "2024-08-15T09:32:17Z",
  updated_at: "2025-02-18T11:42:09Z",
};
export const pollChangesTriggerExamplePayload: {
  payload: TriggerPayload;
} = {
  payload: {
    headers: {},
    queryParameters: {},
    rawBody: { data: null },
    body: {
      data: {
        created: [createdContactRecord],
        updated: [updatedContactRecord],
      },
    },
    pathFragment: "",
    webhookUrls: {},
    webhookApiKeys: {},
    invokeUrl: "",
    executionId: "RXhhbXBsZUV4ZWN1dGlvblJlc3VsdElk",
    customer: {
      id: "testCustomerId",
      name: "Test Customer",
      externalId: "testExternalId",
    },
    instance: { id: "testInstanceId", name: "Test Instance" },
    user: {
      id: "testUserId",
      email: "user@example.com",
      name: "Test User",
      externalId: "testUserExternalId",
    },
    integration: {
      id: "testIntegrationId",
      name: "Test Integration",
      versionSequenceId: "1",
      externalVersion: "",
    },
    flow: { id: "testFlowId", name: "Test Flow", stableId: "testFlowStableId" },
    startedAt: "2024-01-15T00:00:00.000Z",
    globalDebug: false,
  },
};
