export { uploadFile } from "./uploadFile";
export { saveFromUrl } from "./saveFromUrl";
export { downloadFile } from "./downloadFile";
export { deleteFile } from "./deleteFile";
export { copyFile } from "./copyFile";
import { uploadFile } from "./uploadFile";
import { saveFromUrl } from "./saveFromUrl";
import { downloadFile } from "./downloadFile";
import { deleteFile } from "./deleteFile";
import { copyFile } from "./copyFile";
export default { uploadFile, saveFromUrl, downloadFile, deleteFile, copyFile };
