import { input, util } from "@prismatic-io/spectral";
import { toOptionalBoolean } from "../util";
import {
  connectionInput,
  pageNumber,
  pageSize,
  projectId,
  searchString,
  timeout,
  userId,
  workbookId,
} from "./common";
const workbookName = input({
  label: "Workbook Name",
  type: "string",
  required: true,
  comments: "The name of the workbook.",
  example: "My Workbook",
  placeholder: "Enter workbook name",
  clean: util.types.toString,
});
const showTabs = input({
  label: "Show Tabs",
  type: "boolean",
  required: false,
  default: "false",
  comments: "When true, the updated workbook shows views in tabs.",
  clean: toOptionalBoolean,
});
const workbookSearchField = input({
  label: "Search Field",
  type: "string",
  required: true,
  comments: "The field to search.",
  example: `Tags`,
  clean: util.types.toString,
  model: [
    { label: "Name", value: "name" },
    { label: "Owner Name", value: "ownerName" },
    { label: "Tags", value: "tags" },
  ],
});
const filterOperator = input({
  label: "Filter Operator",
  type: "string",
  required: true,
  comments: "The operator to use when searching.",
  example: `eq`,
  clean: util.types.toString,
  model: [
    { label: "Equals", value: "eq" },
    { label: "In", value: "in" },
  ],
});
const uploadSessionId = input({
  label: "Upload Session Id",
  type: "string",
  required: false,
  comments:
    "When committing a file that was uploaded in parts, this value contains the upload session ID generated by a call to Initiate File Upload.",
  clean: util.types.toString,
});
const workbookType = input({
  label: "Workbook Type",
  type: "string",
  required: false,
  comments:
    "twb or twbx to indicate whether the uploaded file is a workbook file (twb) or a packaged workbook file (twbx).",
  model: [
    { label: "", value: "" },
    { label: "twb", value: "twb" },
    { label: "twbx", value: "twbx" },
  ],
  default: "",
  clean: util.types.toString,
});
const overwrite = input({
  label: "Overwrite",
  type: "boolean",
  required: false,
  comments:
    "True to overwrite a workbook that has the same name, or false to fail if the specified workbook already exists.",
  default: "false",
  clean: util.types.toBool,
});
const asJob = input({
  label: "As Job",
  type: "boolean",
  required: false,
  comments:
    "When false, the workbook publishing process runs synchronously and may time out for very large workbooks. When true, the process runs asynchronously and a job starts to perform the publishing process and return the job ID.",
  default: "false",
  clean: util.types.toBool,
});
const skipConnectionCheck = input({
  label: "Skip Connection Check",
  type: "boolean",
  required: false,
  comments:
    "If true, then the Tableau server will not check if a non-published connection of a workbook is reachable.",
  default: "false",
  clean: util.types.toBool,
});
const workbookXml = input({
  label: "Workbook XML",
  type: "code",
  language: "xml",
  required: true,
  example: `<tsRequest>
  <workbook name="workbook-name">
      <project id="project-id"></project>
  </workbook>
</tsRequest>`,
  clean: util.types.toString,
});
const workbookFileContents = input({
  label: "Workbook File Contents",
  type: "data",
  required: true,
  comments: "The twbx file to upload as binary data.",
  clean: util.types.toBufferDataPayload,
});
export const listWorkbooksInputs = {
  timeout,
  pageSize,
  pageNumber,
  tableauConnection: connectionInput,
};
export const searchWorkbooksInputs = {
  searchField: workbookSearchField,
  filterOperator: filterOperator,
  searchString: { ...searchString, example: "Tag 1, Tag 2, My 3rd Tag" },
  timeout,
  tableauConnection: connectionInput,
  pageNumber,
  pageSize,
};
export const getWorkbookInputs = {
  workbookId,
  timeout,
  tableauConnection: connectionInput,
};
export const deleteWorkbookInputs = {
  workbookId,
  timeout,
  tableauConnection: connectionInput,
};
export const publishWorkbookInputs = {
  timeout,
  tableauConnection: connectionInput,
  uploadSessionId,
  workbookType,
  overwrite,
  asJob,
  skipConnectionCheck,
  workbookXml,
  workbookFileContents,
};
export const updateWorkbookInputs = {
  workbookId,
  workbookName,
  projectId,
  userId,
  showTabs,
  timeout,
  tableauConnection: connectionInput,
};
