import { component } from "@prismatic-io/spectral";
import {
  addNoteToInvoice,
  addNoteToItem,
  archiveAccount,
  archiveContact,
  createAccount,
  createAttachment,
  createContact,
  createInvoice,
  createItem,
  deleteAccount,
  deleteInvoice,
  deleteItem,
  getAccount,
  getAttachment,
  getContact,
  getContactHistory,
  getInvoice,
  getItem,
  getItemHistory,
  getPayment,
  getPaymentHistory,
  listAccounts,
  listConnections,
  listContacts,
  listInvoices,
  listItems,
  listPayments,
  payInvoice,
  rawRequest,
  reversePayment,
  sendInvoice,
  updateAccount,
  updateContact,
  updateItem,
  voidInvoice,
} from "./actions";
import connections from "./connections";
import triggers from "./triggers";
import { handleErrors } from "@prismatic-io/spectral/dist/clients/http";
import dataSources from "./dataSources";
export default component({
  key: "xero",
  public: true,
  documentationUrl: "https://prismatic.io/docs/components/xero/",
  display: {
    label: "Xero",
    category: "Application Connectors",
    description:
      "Manage invoices, items, accounts, payments, and more in Xero.",
    iconPath: "icon.png",
  },
  actions: {
    listContacts,
    listConnections,
    getContact,
    archiveContact,
    deleteAccount,
    listAccounts,
    getInvoice,
    getItem,
    deleteInvoice,
    listInvoices,
    deleteItem,
    listItems,
    createContact,
    getContactHistory,
    updateContact,
    createItem,
    getItemHistory,
    addNoteToItem,
    createInvoice,
    sendInvoice,
    voidInvoice,
    addNoteToInvoice,
    createAccount,
    createAttachment,
    getAttachment,
    getPayment,
    getPaymentHistory,
    listPayments,
    payInvoice,
    reversePayment,
    getAccount,
    archiveAccount,
    updateAccount,
    updateItem,
    rawRequest,
  },
  connections,
  dataSources,
  triggers,
  hooks: { error: handleErrors },
});
